### ISSUE TITLE
请教个问题？

### ISSUE THREAD

**Issue by rxmao** [OpenBMB/VisRAG#33]
VisRAG-Gen (MiniCPM-V-2_6) load success!
Enter your query: 怀孕如何系安全带?
Enter the number of documents to retrieve: 500
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/root/private_data/data/mrx/MLLM/VisRAG/scripts/demo/visrag_pipeline/answer.py", line 90, in <module>
    answer = answer_question(images_topk, query)
  File "/root/private_data/data/mrx/MLLM/VisRAG/scripts/demo/visrag_pipeline/answer.py", line 51, in answer_question
    answer = gen_model.chat(
  File "/root/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2_6/modeling_minicpmv.py", line 348, in chat
    inputs = processor(
  File "/root/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2_6/processing_minicpmv.py", line 67, in __call__
    return self._convert_images_texts_to_inputs(image_inputs, text, max_slice_nums=max_slice_nums, use_image_id=use_image_id, max_length=max_length, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2_6/processing_minicpmv.py", line 165, in _convert_images_texts_to_inputs
    input_ids, image_bounds = self._convert(final_text, max_length)
  File "/root/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2_6/processing_minicpmv.py", line 121, in _convert
    image_bounds = torch.hstack(
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 123 but got size 122 for tensor number 1 in the list.

**Comment by rxmao** [comment]
solved
