### ISSUE TITLE
TypeError: MiniCPMV.forward() missing 1 required positional argument: 'data'

### ISSUE THREAD

**Issue by lmmlzn** [OpenBMB/VisRAG#6]
How to resolve the following error?

Traceback (most recent call last):
  File "/data2/ly/VisRAG/src/openmatch/driver/train.py", line 148, in <module>
    main()
  File "/data2/ly/VisRAG/src/openmatch/driver/train.py", line 141, in main
    trainer.train()
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data2/ly/VisRAG/src/openmatch/trainer/dense_trainer.py", line 294, in training_step
    outputs_ = model(query=micro_query, passage=micro_passage, **additional_args)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/ly/VisRAG/src/openmatch/modeling/dense_retrieval_model.py", line 125, in forward
    _, q_reps = self.encode_query(query, **kwargs)
  File "/data2/ly/VisRAG/src/openmatch/modeling/dense_retrieval_model.py", line 231, in encode_query
    return self.encode(qry, self.lm_q, self.head_q, is_query=True, **kwargs)
  File "/data2/ly/VisRAG/src/openmatch/modeling/dense_retrieval_model.py", line 147, in encode
    items_out = model(is_query = is_query, **items, **kwargs)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: MiniCPMV.forward() missing 1 required positional argument: 'data'
  0%|          | 0/30688 [00:00<?, ?it/s]                                                      
[2024-10-17 11:36:49,695] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2055864) of binary: /home/yang_liu/anaconda3/envs/VisRAG/bin/python
Traceback (most recent call last):
  File "/home/yang_liu/anaconda3/envs/VisRAG/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yang_liu/anaconda3/envs/VisRAG/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/openmatch/driver/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-17_11:36:49
  host      : pci-SYS-420GP-TNR
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2055865)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-17_11:36:49
  host      : pci-SYS-420GP-TNR
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2055864)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

Is the command line for training like this correct?

CUDA_VISIBLE_DEVICES=1,2 bash scripts/train_retriever/train.sh 2048 2 2 0.02 1 true false config/deepspeed.json 1e-5 false wmean causal 1 true 2 false /data2/ly/model/MiniCPM-V-2 /data2/ly/VisRAG/data
（/data2/ly/VisRAG/data is like openbmb/VisRAG-Ret-Train-In-domain-data，
There is a data folder inside, which contains files such as train-00000-of-00037.parquet. Is the dataset stored like this correct?

-data
    -data
      -train-00000-of-00037.parquet
）

**Comment by lmmlzn** [comment]
or the model is wrong?

**Comment by tcy6** [comment]
Sorry for this, please allow me some time to check and I will reply as soon as possible.

**Comment by tcy6** [comment]
Alright, I believe I've found the reason, and you're right, you did load the wrong model. The logic we use to load the model is to check whether the `_name_or_path` in `model_dir/config.json` contains `MiniCPM-V-2-0`. However, the parameter in your `MiniCPM-V-2/config.json` has probably been modified to `MiniCPM-V-2`, which caused you to fail to load the customized model code from our repository and instead use the original code from the remote repository. I have now modified the code to enhance the robustness of the logic. Please pull the latest code and see if the issue still exists.

**Comment by lmmlzn** [comment]
> Alright, I believe I've found the reason, and you're right, you did load the wrong model. The logic we use to load the model is to check whether the `_name_or_path` in `model_dir/config.json` contains `MiniCPM-V-2-0`. However, the parameter in your `MiniCPM-V-2/config.json` has probably been modified to `MiniCPM-V-2`, which caused you to fail to load the customized model code from our repository and instead use the original code from the remote repository. I have now modified the code to enhance the robustness of the logic. Please pull the latest code and see if the issue still exists.

Thank you so much! This is indeed the issue. I noticed that the official model name is "openbmb/MiniCPM-V-2" rather than "MiniCPM-V-2-0," which caused the problem.

**Comment by tcy6** [comment]
> > Alright, I believe I've found the reason, and you're right, you did load the wrong model. The logic we use to load the model is to check whether the `_name_or_path` in `model_dir/config.json` contains `MiniCPM-V-2-0`. However, the parameter in your `MiniCPM-V-2/config.json` has probably been modified to `MiniCPM-V-2`, which caused you to fail to load the customized model code from our repository and instead use the original code from the remote repository. I have now modified the code to enhance the robustness of the logic. Please pull the latest code and see if the issue still exists.
> 
> Thank you so much! This is indeed the issue. I noticed that the official model name is "openbmb/MiniCPM-V-2" rather than "MiniCPM-V-2-0," which caused the problem.

You're welcome! I'm also a bit curious—are you trying to reproduce our results? During our training, the batch size was 128. However, I noticed that in your script configuration, the batch size is set to `PER_DEV_BATCH_SIZE` * `GPUS_PER_NODE` = 2 * 2 = 4.

**Comment by lmmlzn** [comment]
> > > Alright, I believe I've found the reason, and you're right, you did load the wrong model. The logic we use to load the model is to check whether the `_name_or_path` in `model_dir/config.json` contains `MiniCPM-V-2-0`. However, the parameter in your `MiniCPM-V-2/config.json` has probably been modified to `MiniCPM-V-2`, which caused you to fail to load the customized model code from our repository and instead use the original code from the remote repository. I have now modified the code to enhance the robustness of the logic. Please pull the latest code and see if the issue still exists.
> > 
> > 
> > Thank you so much! This is indeed the issue. I noticed that the official model name is "openbmb/MiniCPM-V-2" rather than "MiniCPM-V-2-0," which caused the problem.
> 
> You're welcome! I'm also a bit curious—are you trying to reproduce our results? During our training, the batch size was 128. However, I noticed that in your script configuration, the batch size is set to `PER_DEV_BATCH_SIZE` * `GPUS_PER_NODE` = 2 * 2 = 4.

No, I'm just trying to see if I can run the code successfully with a small-scale computing power.

**Comment by tcy6** [comment]
> > > > Alright, I believe I've found the reason, and you're right, you did load the wrong model. The logic we use to load the model is to check whether the `_name_or_path` in `model_dir/config.json` contains `MiniCPM-V-2-0`. However, the parameter in your `MiniCPM-V-2/config.json` has probably been modified to `MiniCPM-V-2`, which caused you to fail to load the customized model code from our repository and instead use the original code from the remote repository. I have now modified the code to enhance the robustness of the logic. Please pull the latest code and see if the issue still exists.
> > > 
> > > 
> > > Thank you so much! This is indeed the issue. I noticed that the official model name is "openbmb/MiniCPM-V-2" rather than "MiniCPM-V-2-0," which caused the problem.
> > 
> > 
> > You're welcome! I'm also a bit curious—are you trying to reproduce our results? During our training, the batch size was 128. However, I noticed that in your script configuration, the batch size is set to `PER_DEV_BATCH_SIZE` * `GPUS_PER_NODE` = 2 * 2 = 4.
> 
> No, I'm just trying to see if I can run the code successfully with a small-scale computing power.

Oh, I see.
